In [1]:
import numpy as np

# Create environment

In [2]:
number_of_states = 16
number_of_terminal_states = 2
number_of_non_terminal_states = number_of_states - number_of_terminal_states

In [3]:
max_number_of_actions = 4

In [4]:
number_of_actions_per_non_terminal_state = np.repeat(a = max_number_of_actions, repeats = number_of_non_terminal_states)
number_of_actions_per_non_terminal_state

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [5]:
number_of_state_action_successor_states = np.ones(shape = [number_of_states, max_number_of_actions], dtype = np.int64)
number_of_state_action_successor_states

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
state_action_successor_state_indices = np.array([1, 0, 14, 4, 2, 1, 0, 5, 2, 2, 1, 6, 4, 14, 3, 7, 5, 0, 3, 8, 6, 1, 4, 9, 6, 2, 5, 10, 8, 3, 7, 11, 9, 4, 7, 12, 10, 5, 8, 13, 10, 6, 9, 15, 12, 7, 11, 11, 13, 8, 11, 12, 15, 9, 12, 13], dtype = np.int64)
state_action_successor_state_indices = np.reshape(a = state_action_successor_state_indices, newshape = (number_of_non_terminal_states, max_number_of_actions, 1))
state_action_successor_state_indices

array([[[ 1],
        [ 0],
        [14],
        [ 4]],

       [[ 2],
        [ 1],
        [ 0],
        [ 5]],

       [[ 2],
        [ 2],
        [ 1],
        [ 6]],

       [[ 4],
        [14],
        [ 3],
        [ 7]],

       [[ 5],
        [ 0],
        [ 3],
        [ 8]],

       [[ 6],
        [ 1],
        [ 4],
        [ 9]],

       [[ 6],
        [ 2],
        [ 5],
        [10]],

       [[ 8],
        [ 3],
        [ 7],
        [11]],

       [[ 9],
        [ 4],
        [ 7],
        [12]],

       [[10],
        [ 5],
        [ 8],
        [13]],

       [[10],
        [ 6],
        [ 9],
        [15]],

       [[12],
        [ 7],
        [11],
        [11]],

       [[13],
        [ 8],
        [11],
        [12]],

       [[15],
        [ 9],
        [12],
        [13]]])

In [7]:
state_action_successor_state_transition_probabilities = np.ones(shape = [number_of_non_terminal_states, max_number_of_actions, 1], dtype = np.float64)
state_action_successor_state_transition_probabilities

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [8]:
state_action_successor_state_rewards = np.ones(shape = [number_of_non_terminal_states, max_number_of_actions, 1], dtype = np.float64) * -1
state_action_successor_state_rewards

array([[[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.]]])

# Set hyperparameters

In [9]:
# Set the number of episodes
number_of_episodes = 10000
# Set the maximum episode length
maximum_episode_length = 200
# Set learning rate alpha
alpha = 0.1
# Set epsilon for our epsilon level of exploration
epsilon = 0.1
# Set discounting factor gamma
discounting_factor_gamma = 1.0
# Set trace decay parameter lambda
trace_decay_lambda = 0.9
# Set the trace update type, 0 = accumulating, 1 = replacing
trace_update_type = 0

# Create value function and policy arrays

In [10]:
state_action_value_function = np.zeros(shape = [number_of_states, max_number_of_actions], dtype = np.float64)
state_action_value_function

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
policy = np.repeat(a = 1.0 / max_number_of_actions, repeats = number_of_non_terminal_states * max_number_of_actions)
policy = np.reshape(a = policy, newshape = (number_of_non_terminal_states, max_number_of_actions))
policy

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

# Create eligibility traces

In [12]:
eligibility_trace = np.zeros(shape = [number_of_states, max_number_of_actions], dtype = np.float64)
eligibility_trace

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Create algorithm

In [13]:
# Set random seed so that everything is reproducible
np.random.seed(seed = 0)

In [14]:
# This function initializes episodes
def initialize_epsiode(number_of_non_terminal_states, eligibility_trace):
    # Reset eligibility traces for new episode
    eligibility_trace = np.zeros_like(a = eligibility_trace)
    
    # Initial state
    initial_state_index = np.random.randint(low = 0, high = number_of_non_terminal_states, dtype = np.int64) # randomly choose an initial state from all non-terminal states

    return initial_state_index, eligibility_trace

In [15]:
# This function selects a policy epsilon-greedily from the state-action-value function
def epsilon_greedy_policy_from_state_action_function(max_number_of_actions, state_action_value_function, epsilon, state_index, policy):
    # Save max state-action value and find the number of actions that have the same max state-action value
    max_action_value = np.max(a = state_action_value_function[state_index, :])
    max_action_count = np.count_nonzero(a = state_action_value_function[state_index, :] == max_action_value)

    # Apportion policy probability across ties equally for state-action pairs that have the same value and zero otherwise
    if max_action_count == max_number_of_actions:
        max_policy_apportioned_probability_per_action = 1.0 / max_action_count
        remaining_apportioned_probability_per_action = 0.0
    else:
        max_policy_apportioned_probability_per_action = (1.0 - epsilon) / max_action_count
        remaining_apportioned_probability_per_action = epsilon / (max_number_of_actions - max_action_count)

    policy[state_index, :] = np.where(state_action_value_function[state_index, :] == max_action_value, max_policy_apportioned_probability_per_action, remaining_apportioned_probability_per_action)

    return policy

In [16]:
# This function loops through episodes and updates the policy
def loop_through_episode(number_of_non_terminal_states, max_number_of_actions, number_of_state_action_successor_states, state_action_successor_state_indices, state_action_successor_state_transition_probabilities, state_action_successor_state_rewards, state_action_value_function, policy, eligibility_trace, alpha, epsilon, discounting_factor_gamma, trace_decay_lambda, trace_update_type, maximum_episode_length, state_index):
    # Loop through episode steps until termination
    for t in range(0, maximum_episode_length):
        # Choose policy for chosen state by epsilon-greedy choosing from the state-action-value function */
        policy = epsilon_greedy_policy_from_state_action_function(max_number_of_actions, state_action_value_function, epsilon, state_index, policy)

        # Get action
        action_index = np.random.choice(a = max_number_of_actions, p = policy[state_index, :])

        # Get reward
        successor_state_transition_index = np.random.choice(a = number_of_state_action_successor_states[state_index, action_index], p = state_action_successor_state_transition_probabilities[state_index, action_index, :])

        # Get reward from state and action
        reward = state_action_successor_state_rewards[state_index, action_index, successor_state_transition_index]

        # Get next state
        next_state_index = state_action_successor_state_indices[state_index, action_index, successor_state_transition_index]
        
        # Check to see if we actioned into a terminal state
        if next_state_index >= number_of_non_terminal_states:
            # Calculate TD error delta
            delta = reward - state_action_value_function[state_index, action_index]

            # Update eligibility traces and state action value function with TD error
            eligibility_trace, state_action_value_function = update_eligibility_trace_and_state_action_value_function(state_index, action_index, delta, number_of_non_terminal_states, max_number_of_actions, alpha, discounting_factor_gamma, trace_decay_lambda, trace_update_type, state_action_value_function, eligibility_trace)

            break; # episode terminated since we ended up in a terminal state
        else:
            # Get next action, using expectation value
            state_value_function_expected_value_on_policy = np.sum(a = policy[next_state_index, :] * state_action_value_function[next_state_index, :])

            # Calculate TD error delta
            delta = reward + discounting_factor_gamma * state_value_function_expected_value_on_policy - state_action_value_function[state_index, action_index]

            # Update eligibility traces and state action value function with TD error
            eligibility_trace, state_action_value_function = update_eligibility_trace_and_state_action_value_function(state_index, action_index, delta, number_of_non_terminal_states, max_number_of_actions, alpha, discounting_factor_gamma, trace_decay_lambda, trace_update_type, state_action_value_function, eligibility_trace)

            # Update state and action to next state and action
            state_index = next_state_index

    return state_action_value_function, policy

In [17]:
# This function updates the eligibility trace and state-action-value function
def update_eligibility_trace_and_state_action_value_function(state_index, action_index, delta, number_of_non_terminal_states, max_number_of_actions, alpha, discounting_factor_gamma, trace_decay_lambda, trace_update_type, state_action_value_function, eligibility_trace):
    # Update eligibility trace
    if trace_update_type == 1: # replacing
        eligibility_trace[state_index, action_index] = 1.0
    else: # accumulating or unknown
        eligibility_trace[state_index, action_index] += 1.0

    # Update state-action-value function
    state_action_value_function += alpha * delta * eligibility_trace
    eligibility_trace *= discounting_factor_gamma * trace_decay_lambda

    return eligibility_trace, state_action_value_function

In [18]:
def on_policy_stochastic_eligibility_trace_expected_sarsa_lambda(number_of_non_terminal_states, max_number_of_actions, number_of_state_action_successor_states, state_action_successor_state_indices, state_action_successor_state_transition_probabilities, state_action_successor_state_rewards, state_action_value_function, policy, eligibility_trace, alpha, epsilon, discounting_factor_gamma, maximum_episode_length):
    for episode in range(0, number_of_episodes):
        # Initialize episode to get initial state
        initial_state_index, eligibility_trace = initialize_epsiode(number_of_non_terminal_states, eligibility_trace)

        # Loop through episode and update the policy
        state_action_value_function, policy = loop_through_episode(number_of_non_terminal_states, max_number_of_actions, number_of_state_action_successor_states, state_action_successor_state_indices, state_action_successor_state_transition_probabilities, state_action_successor_state_rewards, state_action_value_function, policy, eligibility_trace, alpha, epsilon, discounting_factor_gamma, trace_decay_lambda, trace_update_type, maximum_episode_length, initial_state_index)
    
    return state_action_value_function, policy

# Run algorithm

In [19]:
# Print initial arrays
print("\nInitial state-action value function")
print(state_action_value_function)

print("\nInitial policy")
print(policy)

# Run on policy temporal difference sarsa
state_action_value_function, policy = on_policy_stochastic_eligibility_trace_expected_sarsa_lambda(number_of_non_terminal_states, max_number_of_actions, number_of_state_action_successor_states, state_action_successor_state_indices, state_action_successor_state_transition_probabilities, state_action_successor_state_rewards, state_action_value_function, policy, eligibility_trace, alpha, epsilon, discounting_factor_gamma, maximum_episode_length)

# Print final results
print("\nFinal state-action value function")
print(state_action_value_function)

print("\nFinal policy")
print(policy)


Initial state-action value function
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Initial policy
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]

Final state-action value function
[[-3.36930478 -2.19619019 -1.         -3.33086265]
 [-4.38027994 -3.31830747 -2.19686878 -4.16745228]
 [-4.3897442  -4.19385815 -3.40334765 -3.38270328]
 [-3.33862362 -1.         -2.19511778 -3.37545725]
 [-4.30305083 -2.19652985 -2.19940086 -4.16851447]
 [-3.4002236  -3.38022168 -3.34388115 -3.34063848]
 [-3.38296766 -4.43888286 -4.33973086 -2.1