In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)
print(np.__version__)
np.set_printoptions(threshold = np.inf)

tf.enable_eager_execution()
tf.executing_eagerly()

/usr/local/envs/py3env/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.12.0
1.14.0


True

In [2]:
number_of_sequences = 7
sequence_length = 5
number_of_features = 3

In [3]:
X = np.random.randn(number_of_sequences, sequence_length, number_of_features)
# X = np.arange(number_of_sequences * sequence_length * number_of_features, dtype = np.float64).reshape(number_of_sequences, sequence_length, number_of_features)
X

array([[[-0.83615598, -0.12834801,  0.30192741],
        [-0.22310588,  0.19912519,  0.75330085],
        [-0.82476173,  0.55339509,  1.02916109],
        [ 0.895188  , -0.34416919, -0.32811474],
        [ 0.44636986, -1.49928615, -1.1189625 ]],

       [[-1.07043421, -0.48200063, -0.78466451],
        [ 1.19840494,  1.73781682,  0.69771975],
        [-1.44312287,  0.82571467, -0.76498676],
        [ 1.1250593 ,  0.18569901,  0.71799716],
        [ 0.14723532,  1.1760961 ,  0.50878075]],

       [[ 0.89208506,  1.35587651,  0.10168686],
        [ 0.50626182, -0.20924821, -0.12077236],
        [ 0.74267411, -0.52109196,  1.01307836],
        [-0.14237112, -0.54045478,  1.38234983],
        [-1.40906981,  0.52532241, -0.50505042]],

       [[-0.20106122,  1.18240575,  1.31866197],
        [ 1.76921362, -0.77869568, -0.56981356],
        [ 0.38549032,  0.06455597, -1.49879216],
        [ 0.06218173, -0.87576917, -0.12820259],
        [-0.01978002, -0.81485399, -0.41261347]],

       [[-0.

In [4]:
X_batch_time = np.transpose(X.reshape(number_of_sequences * sequence_length, number_of_features))
X_batch_time

array([[-0.83615598, -0.22310588, -0.82476173,  0.895188  ,  0.44636986,
        -1.07043421,  1.19840494, -1.44312287,  1.1250593 ,  0.14723532,
         0.89208506,  0.50626182,  0.74267411, -0.14237112, -1.40906981,
        -0.20106122,  1.76921362,  0.38549032,  0.06218173, -0.01978002,
        -0.32538092, -0.85830762, -1.28556195, -0.20112383, -1.6757011 ,
         0.69263443,  0.40042493, -1.13552464, -1.32316203,  0.11760018,
        -0.8749159 ,  0.35949477,  0.76143917, -0.76033357, -0.07015045],
       [-0.12834801,  0.19912519,  0.55339509, -0.34416919, -1.49928615,
        -0.48200063,  1.73781682,  0.82571467,  0.18569901,  1.1760961 ,
         1.35587651, -0.20924821, -0.52109196, -0.54045478,  0.52532241,
         1.18240575, -0.77869568,  0.06455597, -0.87576917, -0.81485399,
         0.60610816, -0.63623283, -0.80931457, -0.5571892 ,  2.31354984,
        -0.3422228 , -0.01118558,  0.56296273,  0.08751321,  0.4747673 ,
        -0.82695819,  1.14139306,  1.4010594 , -1.

In [5]:
X_batch_time.shape

(3, 35)

In [6]:
X_batch_time_mean = np.mean(X_batch_time, axis = 1)
X_batch_time_mean

array([-0.11937907,  0.0551248 ,  0.00466804])

In [7]:
X_batch_time_centered = np.transpose(X_batch_time) - X_batch_time_mean
X_batch_time_centered

array([[-0.71677691, -0.18347281,  0.29725937],
       [-0.10372681,  0.14400039,  0.7486328 ],
       [-0.70538266,  0.49827029,  1.02449304],
       [ 1.01456707, -0.39929398, -0.33278278],
       [ 0.56574892, -1.55441095, -1.12363054],
       [-0.95105515, -0.53712543, -0.78933256],
       [ 1.31778401,  1.68269203,  0.69305171],
       [-1.32374381,  0.77058987, -0.7696548 ],
       [ 1.24443837,  0.13057421,  0.71332912],
       [ 0.26661439,  1.1209713 ,  0.50411271],
       [ 1.01146413,  1.30075171,  0.09701882],
       [ 0.62564088, -0.26437301, -0.1254404 ],
       [ 0.86205317, -0.57621676,  1.00841032],
       [-0.02299205, -0.59557958,  1.37768179],
       [-1.28969074,  0.47019761, -0.50971846],
       [-0.08168216,  1.12728095,  1.31399393],
       [ 1.88859268, -0.83382048, -0.5744816 ],
       [ 0.50486938,  0.00943117, -1.50346021],
       [ 0.18156079, -0.93089397, -0.13287064],
       [ 0.09959904, -0.86997879, -0.41728151],
       [-0.20600186,  0.55098336, -0.017

In [8]:
np.matmul(np.transpose(X_batch_time_centered), X_batch_time_centered) / (number_of_sequences * sequence_length - 1)

array([[ 0.76209202, -0.02599972,  0.1006632 ],
       [-0.02599972,  0.90208752,  0.26962102],
       [ 0.1006632 ,  0.26962102,  0.8277791 ]])

In [9]:
cov_batch_time = np.cov(X_batch_time)
cov_batch_time

array([[ 0.76209202, -0.02599972,  0.1006632 ],
       [-0.02599972,  0.90208752,  0.26962102],
       [ 0.1006632 ,  0.26962102,  0.8277791 ]])

In [10]:
cov_batch_time.shape

(3, 3)

In [11]:
x_batch_features = np.transpose(np.stack(list(map(lambda x: np.transpose(X[x, :, :]), np.arange(number_of_sequences))), axis = 0).reshape(number_of_sequences * number_of_features, sequence_length))
x_batch_features

array([[-0.83615598, -0.12834801,  0.30192741, -1.07043421, -0.48200063,
        -0.78466451,  0.89208506,  1.35587651,  0.10168686, -0.20106122,
         1.18240575,  1.31866197, -0.32538092,  0.60610816, -0.01294615,
         0.69263443, -0.3422228 ,  0.17000911, -0.8749159 , -0.82695819,
         1.63661316],
       [-0.22310588,  0.19912519,  0.75330085,  1.19840494,  1.73781682,
         0.69771975,  0.50626182, -0.20924821, -0.12077236,  1.76921362,
        -0.77869568, -0.56981356, -0.85830762, -0.63623283,  0.34249156,
         0.40042493, -0.01118558,  1.21940222,  0.35949477,  1.14139306,
         0.24308949],
       [-0.82476173,  0.55339509,  1.02916109, -1.44312287,  0.82571467,
        -0.76498676,  0.74267411, -0.52109196,  1.01307836,  0.38549032,
         0.06455597, -1.49879216, -1.28556195, -0.80931457, -0.37455713,
        -1.13552464,  0.56296273, -0.2075209 ,  0.76143917,  1.4010594 ,
         1.09740284],
       [ 0.895188  , -0.34416919, -0.32811474,  1.1250593 

In [12]:
x_batch_features.shape

(5, 21)

In [13]:
cov_batch_features = np.cov(x_batch_features)
cov_batch_features

array([[ 0.67907284, -0.27218509, -0.01522113, -0.27254151, -0.09194904],
       [-0.27218509,  0.59656383,  0.25756871,  0.00309128, -0.05205706],
       [-0.01522113,  0.25756871,  0.87397584, -0.13013033, -0.32038212],
       [-0.27254151,  0.00309128, -0.13013033,  0.63684263,  0.29473412],
       [-0.09194904, -0.05205706, -0.32038212,  0.29473412,  1.19380066]])

In [14]:
cov_batch_features.shape

(5, 5)

In [15]:
absolute_error = tf.constant(value = X, dtype = tf.float64)
current_batch_size = tf.shape(input = absolute_error, out_type = tf.int64)[0]
params = {}
params["sequence_length"] = sequence_length
number_of_features = 3

# Time based
absolute_error_reshaped_batch_time = tf.reshape(tensor = absolute_error, shape = [current_batch_size * params["sequence_length"], number_of_features])
print("absolute_error_reshaped_batch_time = \n{}".format(absolute_error_reshaped_batch_time))

absolute_error_mean_batch_time = tf.reduce_mean(input_tensor = absolute_error_reshaped_batch_time, axis = 0)
print("absolute_error_mean_batch_time = \n{}".format(absolute_error_mean_batch_time))

absolute_error_reshaped_batch_time_centered = absolute_error_reshaped_batch_time - absolute_error_mean_batch_time
print("absolute_error_reshaped_batch_time_centered = \n{}".format(absolute_error_reshaped_batch_time_centered))

absolute_error_reshaped_batch_time_covariance_matrix = tf.matmul(a = absolute_error_reshaped_batch_time_centered, 
                                                                 b = absolute_error_reshaped_batch_time_centered, 
                                                                 transpose_a = True) / tf.cast(x = current_batch_size * params["sequence_length"] - 1, dtype = tf.float64)
print("absolute_error_reshaped_batch_time_covariance_matrix = \n{}".format(absolute_error_reshaped_batch_time_covariance_matrix))

absolute_error_reshaped_batch_time_inverse_covariance_matrix = tf.matrix_inverse(input = absolute_error_reshaped_batch_time_covariance_matrix)
print("absolute_error_reshaped_batch_time_inverse_covariance_matrix = \n{}".format(absolute_error_reshaped_batch_time_inverse_covariance_matrix))

# Features based
absolute_error_mapped_batch_features = tf.map_fn(fn = lambda x: tf.transpose(a = absolute_error[x, :, :]), 
                                                   elems = tf.range(start = 0, limit = current_batch_size, dtype = tf.int64), 
                                                   dtype = tf.float64)
print("absolute_error_mapped_batch_features = \n{}".format(absolute_error_mapped_batch_features))
absolute_error_reshaped_batch_features = tf.reshape(tensor = absolute_error_mapped_batch_features, shape = [current_batch_size * number_of_features, params["sequence_length"]])
print("absolute_error_reshaped_batch_features = \n{}".format(absolute_error_reshaped_batch_features))

absolute_error_mean_batch_features = tf.reduce_mean(input_tensor = absolute_error_reshaped_batch_features, axis = 0)
print("absolute_error_mean_batch_features = \n{}".format(absolute_error_mean_batch_features))

absolute_error_reshaped_batch_features_centered = absolute_error_reshaped_batch_features - absolute_error_mean_batch_features
print("absolute_error_reshaped_batch_features_centered = \n{}".format(absolute_error_reshaped_batch_features_centered))

absolute_error_reshaped_batch_features_covariance_matrix = tf.matmul(a = absolute_error_reshaped_batch_features_centered, 
                                                                     b = absolute_error_reshaped_batch_features_centered, 
                                                                     transpose_a = True) / tf.cast(x = current_batch_size * number_of_features - 1, dtype = tf.float64)
print("absolute_error_reshaped_batch_features_covariance_matrix = \n{}".format(absolute_error_reshaped_batch_features_covariance_matrix))

absolute_error_reshaped_batch_features_inverse_covariance_matrix = tf.matrix_inverse(input = absolute_error_reshaped_batch_features_covariance_matrix)
print("absolute_error_reshaped_batch_features_inverse_covariance_matrix = \n{}".format(absolute_error_reshaped_batch_features_inverse_covariance_matrix))

absolute_error_reshaped_batch_time = 
[[-0.83615598 -0.12834801  0.30192741]
 [-0.22310588  0.19912519  0.75330085]
 [-0.82476173  0.55339509  1.02916109]
 [ 0.895188   -0.34416919 -0.32811474]
 [ 0.44636986 -1.49928615 -1.1189625 ]
 [-1.07043421 -0.48200063 -0.78466451]
 [ 1.19840494  1.73781682  0.69771975]
 [-1.44312287  0.82571467 -0.76498676]
 [ 1.1250593   0.18569901  0.71799716]
 [ 0.14723532  1.1760961   0.50878075]
 [ 0.89208506  1.35587651  0.10168686]
 [ 0.50626182 -0.20924821 -0.12077236]
 [ 0.74267411 -0.52109196  1.01307836]
 [-0.14237112 -0.54045478  1.38234983]
 [-1.40906981  0.52532241 -0.50505042]
 [-0.20106122  1.18240575  1.31866197]
 [ 1.76921362 -0.77869568 -0.56981356]
 [ 0.38549032  0.06455597 -1.49879216]
 [ 0.06218173 -0.87576917 -0.12820259]
 [-0.01978002 -0.81485399 -0.41261347]
 [-0.32538092  0.60610816 -0.01294615]
 [-0.85830762 -0.63623283  0.34249156]
 [-1.28556195 -0.80931457 -0.37455713]
 [-0.20112383 -0.5571892  -0.37874052]
 [-1.6757011   2.31354984 

In [16]:
number_of_test_sequences = 8

In [17]:
y = np.random.randn(number_of_test_sequences, sequence_length, number_of_features)
# test_absolute_error = np.arange(number_of_sequences * sequence_length * number_of_features, dtype = np.float64).reshape(number_of_sequences, sequence_length, number_of_features)
y

array([[[-1.32507344,  1.25739454,  1.78977529],
        [-1.55959305, -1.47463596,  0.35639039],
        [-0.53225582, -0.36652642, -0.84054995],
        [ 0.56465156,  0.70025218, -0.50302822],
        [ 0.27958864,  0.8620938 , -1.35309205]],

       [[-1.15649512, -1.00025417,  0.80277805],
        [-0.70274839,  0.92306629, -1.80035787],
        [-1.58154326,  1.0473085 ,  0.31098267],
        [-0.72718705, -0.7171526 ,  0.08965037],
        [-0.10179273,  0.21889732,  0.61992428]],

       [[ 0.01714146,  0.2021021 , -0.49771569],
        [-2.62598153, -0.39068654,  1.23224617],
        [-0.74491121,  0.04667401,  0.15678677],
        [-0.11865527, -0.10544222, -0.17909211],
        [-0.48988829,  0.67219371,  0.06324813]],

       [[-1.93349504,  0.15740151,  0.05498592],
        [-0.2701429 , -0.11608225, -0.65554017],
        [-0.19809376, -0.33151086,  1.20054207],
        [ 0.35320851, -1.95414558,  0.4015733 ],
        [ 1.25748322,  0.12703432,  0.54906465]],

       [[-0.

In [18]:
y.shape

(8, 5, 3)

In [19]:
test_absolute_error = tf.constant(value = y, dtype = tf.float64)
current_batch_size = tf.shape(input = test_absolute_error, out_type = tf.int64)[0]

def mahalanobis_distance(error_vectors, mean, inverse_covariance_matrix):
  
  return

# Time based
test_absolute_error_reshaped_batch_time = tf.reshape(tensor = test_absolute_error, shape = [current_batch_size * params["sequence_length"], number_of_features])
print("test_absolute_error_reshaped_batch_time = \n{}".format(test_absolute_error_reshaped_batch_time))

test_absolute_error_reshaped_batch_time_centered = test_absolute_error_reshaped_batch_time - absolute_error_mean_batch_time
print("test_absolute_error_reshaped_batch_time_centered = \n{}".format(test_absolute_error_reshaped_batch_time_centered))

mahalanobis_right_matrix_product_batch_time = tf.matmul(a = absolute_error_reshaped_batch_time_inverse_covariance_matrix, 
                                                        b = test_absolute_error_reshaped_batch_time_centered,
                                                        transpose_b = True)
print("mahalanobis_right_matrix_product_batch_time = \n{}".format(mahalanobis_right_matrix_product_batch_time))


mahalanobis_distance_vectorized_batch_time = tf.matmul(a = test_absolute_error_reshaped_batch_time_centered, 
                                                        b = mahalanobis_right_matrix_product_batch_time)
print("mahalanobis_distance_vectorized_batch_time = \n{}".format(mahalanobis_distance_vectorized_batch_time))
print("mahalanobis_distance_vectorized_batch_time.shape = \n{}".format(mahalanobis_distance_vectorized_batch_time.shape))

mahalanobis_distance_batch_time = tf.diag_part(input = mahalanobis_distance_vectorized_batch_time)
print("mahalanobis_distance_batch_time = \n{}".format(mahalanobis_distance_batch_time))
print("mahalanobis_distance_batch_time.shape = \n{}".format(mahalanobis_distance_batch_time.shape))

alternate_mahalanobis_distance_batch_time = tf.squeeze(input = tf.map_fn(fn = lambda x: tf.matmul(a = tf.expand_dims(input = test_absolute_error_reshaped_batch_time_centered[x, :], axis = 0), 
                                               b = tf.matmul(a = absolute_error_reshaped_batch_time_inverse_covariance_matrix, 
                                                             b = tf.expand_dims(input = test_absolute_error_reshaped_batch_time_centered[x, :], axis = 0),
                                                             transpose_b = True)),
                                         elems = tf.range(start = 0, limit = current_batch_size * params["sequence_length"], dtype = tf.int64),
                                         dtype = tf.float64),
                       axis = [1, 2])
print("alternate_mahalanobis_distance_batch_time = \n{}".format(alternate_mahalanobis_distance_batch_time))
print("alternate_mahalanobis_distance_batch_time.shape = \n{}".format(alternate_mahalanobis_distance_batch_time.shape))

test_absolute_error_reshaped_batch_time = 
[[-1.32507344  1.25739454  1.78977529]
 [-1.55959305 -1.47463596  0.35639039]
 [-0.53225582 -0.36652642 -0.84054995]
 [ 0.56465156  0.70025218 -0.50302822]
 [ 0.27958864  0.8620938  -1.35309205]
 [-1.15649512 -1.00025417  0.80277805]
 [-0.70274839  0.92306629 -1.80035787]
 [-1.58154326  1.0473085   0.31098267]
 [-0.72718705 -0.7171526   0.08965037]
 [-0.10179273  0.21889732  0.61992428]
 [ 0.01714146  0.2021021  -0.49771569]
 [-2.62598153 -0.39068654  1.23224617]
 [-0.74491121  0.04667401  0.15678677]
 [-0.11865527 -0.10544222 -0.17909211]
 [-0.48988829  0.67219371  0.06324813]
 [-1.93349504  0.15740151  0.05498592]
 [-0.2701429  -0.11608225 -0.65554017]
 [-0.19809376 -0.33151086  1.20054207]
 [ 0.35320851 -1.95414558  0.4015733 ]
 [ 1.25748322  0.12703432  0.54906465]
 [-0.21004514  0.32571088 -0.49762493]
 [ 0.62695912 -0.44152707  0.79880293]
 [ 0.19009128 -1.28964257 -2.01535309]
 [-0.68321487  0.22666433 -1.23565941]
 [ 1.01422191 -0.1625

In [ ]:
# with tf.Session() as sess:
#     a, b = sess.run([absolute_error_reshaped_batch_time_covariance_matrix, absolute_error_reshaped_batch_features_covariance_matrix])
    
#     print("a = \n{}".format(a))
#     print("a.shape = \n{}".format(a.shape))
    
#     print("b = \n{}".format(b))
#     print("b.shape = \n{}".format(b.shape))