In [1]:
import numpy as np

# Create environment

In [2]:
number_of_states = 8

In [3]:
number_of_bandits = 10

In [4]:
global_bandit_mean_mean = 0.0
global_bandit_mean_variance = 1.0

bandit_mean = np.random.normal(loc = global_bandit_mean_mean, scale = np.sqrt(global_bandit_mean_variance), size = number_of_states * number_of_bandits)
bandit_mean = bandit_mean.reshape(number_of_states, number_of_bandits)
bandit_mean

array([[ 0.97769822, -0.95743347,  1.23151506, -0.61025123,  0.49222511,
        -1.03686477, -0.10894172,  0.71237699, -0.13493995,  0.65384896],
       [ 1.20738252, -0.45827285,  0.67056061, -2.12437064, -0.85994336,
        -1.12569576,  2.15337041,  1.06479789,  1.6433249 ,  1.00446276],
       [ 0.86270704, -0.64426033,  1.98798016, -0.82591445, -0.24048806,
        -0.10600849,  1.49507224, -0.62041518,  0.1753965 , -1.35948718],
       [-0.87054276, -0.16610892, -0.72700421,  1.25727616,  0.69112453,
        -0.72581363, -0.34268559, -0.08943292, -1.07181379, -0.88667207],
       [ 0.84000859, -1.34853052,  0.18606458, -0.15302866, -0.43935007,
         1.2407873 , -0.45009704,  0.75279305,  0.14540684, -1.70121639],
       [-0.11609372,  0.38242081, -0.4006153 ,  1.5709845 ,  0.61559163,
         1.05404329, -0.64900393, -1.99388633,  0.07495446, -0.2431281 ],
       [ 0.18599669,  0.7386674 , -0.61888697,  0.58111699,  0.47827546,
        -0.03025682, -0.56950803, -0.01848738

In [5]:
global_bandit_variance_mean = 1.0
global_bandit_variance_variance = 0.0

bandit_variance = np.random.normal(loc = global_bandit_variance_mean, scale = np.sqrt(global_bandit_variance_variance), size = number_of_states * number_of_bandits)
bandit_variance = bandit_variance.reshape(number_of_states, number_of_bandits)
bandit_variance

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
bandit_stochastic_change_frequencies = np.repeat(a = 201, repeats = number_of_bandits)
bandit_stochastic_change_frequencies

array([201, 201, 201, 201, 201, 201, 201, 201, 201, 201])

In [7]:
bandit_stochastic_change_counter = np.zeros(shape = [number_of_bandits], dtype = np.int64)
bandit_stochastic_change_counter

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Set hyperparameters

In [8]:
# Set the number of iterations
number_of_iterations = 2000
# Set learning rate alpha
alpha = 0.1
# Set epsilon for our epsilon level of exploration
epsilon = 0.1
# Set action selection type (greedy, epsilon-greedy, upper-confidence-bound)
action_selection_type = 1
# Set action value update type (sample-average, biased constant step-size, unbiased constant step-size)
action_value_update_type = 2

# Create value function and policy arrays

In [9]:
state_action_value_function = np.zeros(shape = [number_of_states, number_of_bandits], dtype = np.float64)
state_action_value_function

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
action_count = np.zeros(shape = [number_of_states, number_of_bandits], dtype = np.int64)
action_count

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
action_trace = np.zeros(shape = [number_of_states, number_of_bandits], dtype = np.float64)
action_trace

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
policy = np.repeat(a = 1.0 / number_of_bandits, repeats = number_of_states * number_of_bandits)
policy = policy.reshape(number_of_states, number_of_bandits)
policy

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]])

# Create algorithm

In [13]:
# Set random seed so that everything is reproducible
np.random.seed(seed = 0)

In [14]:
# This function loops through iterations and updates the policy
def loop_through_iterations(number_of_iterations, number_of_states, number_of_bandits, bandit_mean, bandit_variance, bandit_stochastic_change_frequencies, bandit_stochastic_change_counter, global_bandit_mean_mean, global_bandit_mean_variance, global_bandit_variance_mean, global_bandit_variance_variance, state_action_value_function, action_count, action_trace, policy, alpha, epsilon, action_selection_type, action_value_update_type):
    # Loop through iterations until termination
    for t in range(0, number_of_iterations):
        # Get random state
        state_index = np.random.randint(number_of_states)
    
        # Choose policy by epsilon-greedy choosing from the action-value function
        policy = update_policy_from_state_action_value_function(state_index, number_of_bandits, state_action_value_function, action_count, t + 1, epsilon, action_selection_type, policy);

        # Get action
        action_index = np.random.choice(a = number_of_bandits, p = policy[state_index, :])

        # Get reward from action
        reward = np.random.normal(loc = bandit_mean[state_index, action_index], scale = np.sqrt(bandit_variance[state_index, action_index]))

        # Update action count
        action_count[state_index, action_index] += 1

        # Update action-value function
        if action_value_update_type == 0: # sample-average method
            state_action_value_function[state_index, action_index] += (1.0 / action_count[state_index, action_index]) * (reward - state_action_value_function[state_index, action_index]);
        elif action_value_update_type == 1: # biased constant step-size
            state_action_value_function[state_index, action_index] += alpha * (reward - state_action_value_function[state_index, action_index]);
        elif action_value_update_type == 2: # unbiased constant step-size
            # Update action trace
            action_trace[state_index, action_index] += alpha * (1.0 - action_trace[state_index, action_index]);

            state_action_value_function[state_index, action_index] += (alpha / action_trace[state_index, action_index]) * (reward - state_action_value_function[state_index, action_index]);

        # Mutate bandit statistics
        for i in range(number_of_bandits):
            if bandit_stochastic_change_frequencies[i] > 0:
                bandit_stochastic_change_counter[i] += 1

                if bandit_stochastic_change_counter[i] == bandit_stochastic_change_frequencies[i]:
                    bandit_mean[:, i] = np.random.normal(loc = global_bandit_mean_mean, scale = np.sqrt(global_bandit_mean_variance), size = number_of_states)
                    bandit_variance[:, i] = np.random.normal(loc = global_bandit_variance_mean, scale = np.sqrt(global_bandit_variance_variance), size = number_of_states)

                    bandit_stochastic_change_counter[i] = 0

    return bandit_mean, bandit_variance, state_action_value_function, policy

In [15]:
# This function updates policy as some function of action-value function
def update_policy_from_state_action_value_function(state_index, number_of_bandits, state_action_value_function, action_count, iteration_count, epsilon, action_selection_type, policy):
    # Calculate action value depending on action selection type
    if action_selection_type == 0 or action_selection_type == 1: # greedy or epsilon-greedy
        action_value = state_action_value_function[state_index, :]
    elif action_selection_type == 2: # upper-confidence-bound
        min_count_idx = np.argmin(a = state_action_value_function[state_index, :])
        if min_count_idx == 0:
            policy[state_index, :] = np.where(np.arange(number_of_bandits) == min_count_idx, 1.0, 0.0)
            return policy
        else:
            action_value = state_action_value_function[state_index, :] + epsilon * np.sqrt(np.log(iteration_count) / action_count)
    
    # Save max action value and find the number of actions that have the same max action value
    max_action_value = np.max(a = state_action_value_function[state_index, :])
    max_action_count = np.count_nonzero(a = state_action_value_function[state_index, :] == max_action_value)

    # Apportion policy probability across ties equally for state-action pairs that have the same value and zero otherwise
    if action_selection_type == 1: # epsilon-greedy
        if max_action_count == number_of_bandits:
            max_policy_apportioned_probability_per_action = 1.0 / max_action_count
            remaining_apportioned_probability_per_action = 0.0
        else:
            max_policy_apportioned_probability_per_action = (1.0 - epsilon) / max_action_count
            remaining_apportioned_probability_per_action = epsilon / (number_of_bandits - max_action_count)
    elif action_selection_type == 0 or action_selection_type == 2: # greedy or upper-confidence-bound
        max_policy_apportioned_probability_per_action = 1.0 / max_action_count
        remaining_apportioned_probability_per_action = 0.0

    policy[state_index, :] = np.where(action_value == max_action_value, max_policy_apportioned_probability_per_action, remaining_apportioned_probability_per_action)

    return policy

In [16]:
def stochastic_multi_armed_contextual_bandits(number_of_iterations, number_of_states, number_of_bandits, bandit_mean, bandit_variance, bandit_stochastic_change_frequencies, bandit_stochastic_change_counter, global_bandit_mean_mean, global_bandit_mean_variance, global_bandit_variance_mean, global_bandit_variance_variance, state_action_value_function, action_count, action_trace, policy, alpha, epsilon, action_selection_type, action_value_update_type):
    # Loop through iterations and update the policy
    bandit_mean, bandit_variance, state_action_value_function, policy = loop_through_iterations(number_of_iterations, number_of_states, number_of_bandits, bandit_mean, bandit_variance, bandit_stochastic_change_frequencies, bandit_stochastic_change_counter, global_bandit_mean_mean, global_bandit_mean_variance, global_bandit_variance_mean, global_bandit_variance_variance, state_action_value_function, action_count, action_trace, policy, alpha, epsilon, action_selection_type, action_value_update_type)
    
    return bandit_mean, bandit_variance, state_action_value_function, policy

# Run algorithm

In [17]:
# Print initial arrays
print("\nInitial bandit mean")
print(bandit_mean)

print("\nInitial bandit variance")
print(bandit_variance)

print("\nInitial state-action value function")
print(state_action_value_function)

print("\nInitial policy")
print(policy)

# Run on policy temporal difference sarsa
bandit_mean, bandit_variance, state_action_value_function, policy = stochastic_multi_armed_contextual_bandits(number_of_iterations, number_of_states, number_of_bandits, bandit_mean, bandit_variance, bandit_stochastic_change_frequencies, bandit_stochastic_change_counter, global_bandit_mean_mean, global_bandit_mean_variance, global_bandit_variance_mean, global_bandit_variance_variance, state_action_value_function, action_count, action_trace, policy, alpha, epsilon, action_selection_type, action_value_update_type)

# Print final results
print("\nFinal bandit mean")
print(bandit_mean)

print("\nFinal bandit variance")
print(bandit_variance)

print("\nFinal state-action value function")
print(state_action_value_function)

print("\nFinal policy")
print(policy)


Initial bandit mean
[[ 0.97769822 -0.95743347  1.23151506 -0.61025123  0.49222511 -1.03686477
  -0.10894172  0.71237699 -0.13493995  0.65384896]
 [ 1.20738252 -0.45827285  0.67056061 -2.12437064 -0.85994336 -1.12569576
   2.15337041  1.06479789  1.6433249   1.00446276]
 [ 0.86270704 -0.64426033  1.98798016 -0.82591445 -0.24048806 -0.10600849
   1.49507224 -0.62041518  0.1753965  -1.35948718]
 [-0.87054276 -0.16610892 -0.72700421  1.25727616  0.69112453 -0.72581363
  -0.34268559 -0.08943292 -1.07181379 -0.88667207]
 [ 0.84000859 -1.34853052  0.18606458 -0.15302866 -0.43935007  1.2407873
  -0.45009704  0.75279305  0.14540684 -1.70121639]
 [-0.11609372  0.38242081 -0.4006153   1.5709845   0.61559163  1.05404329
  -0.64900393 -1.99388633  0.07495446 -0.2431281 ]
 [ 0.18599669  0.7386674  -0.61888697  0.58111699  0.47827546 -0.03025682
  -0.56950803 -0.01848738 -0.0463772  -0.07039535]
 [-1.0230011  -0.72050413 -1.32661279 -0.03016345  0.60687215 -1.136144
  -1.78557353  0.58456567 -0.3286